language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

install: skip
script: pip install .

jobs:
  include:
    - stage: deploy
      if: branch = master
      script:
        - echo "Deploying version 0.0.${TRAVIS_BUILD_NUMBER}"
