language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

install: skip
script: pip install .

jobs:
  include:
    - stage: deploy
      if: branch = master
      script:
        - export VERSION="${MAJOR_VERSION}.${MINOR_VERSION}.$((${TRAVIS_BUILD_NUMBER} - ${BUILD_NUMBER_SHIFT}))"
        - echo "Deploying version ${VERSION}"

env:
  - MAJOR_VERSION=0   MINOR_VERSION=0   BUILD_NUMBER_SHIFT=5